name: Pylint

on:
  push:
    branches: [ TEST ]
  pull_request:
    branches: [ TEST ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install pylint
      run: pip install pylint
    
    - name: Run pylint
      run: pylint --disable=all --enable=E,W,F *.py
