name: 🧪 Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    name: 🧪 Test Job
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
    
    - name: 🧪 Test step
      run: |
        echo "✅ Test workflow is working!"
        echo "Now you can see 'Run workflow' button in Actions tab"
